services:
  - type: web
    name: flappy777-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FB_PROJECT_ID
        sync: false
      - key: FB_CLIENT_EMAIL
        sync: false
      - key: FB_PRIVATE_KEY
        sync: false